### ISSUE TITLE
Duplexer error when calling store.createWriteStream with modern level version

### ISSUE THREAD

**Issue by lewiscowper** [juliangruber/level-store#17]
# level-store issues so far with modern leveldb implementation

[Gist of this issue](https://gist.github.com/lewiscowper/7ea968aaf076424ec130d9280627e75a)

I updated all outdated dependencies and switched to `^x.y.z` dependency resolution in the `package.json` because I had other things depending on a much higher `level` version.

## `this.db.createWriteStream is not a function` ([at this line ](https://github.com/juliangruber/level-store/blob/master/index.js#L126))

[Live tonic link reproducing this issue](https://tonicdev.com/lewiscowper/576a31cc68bcf113007c70f0) (shift + return to run the notebook)

This is because `levelup` removed createWriteStream and switched to community implementations [see here](https://github.com/Level/levelup#writeStreams).

I forked and added one of them (`level-write-stream`). You can see that [here](https://github.com/lewiscowper/level-store/blob/master/index.js#L127).

## `reader.on is not a function` (inside duplexer, called [at this line](https://github.com/juliangruber/level-store/blob/master/index.js#L128)

This is what I'm presuming can now be fixed with native Node duplex streams, but I'm not sure.

**Comment by juliangruber** [comment]
try release 3.11.0, it now works with recent level :)
